# fly.toml app configuration file generated for rethinkdb-dev on 2023-08-09T16:18:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rethinkdb-dev"
primary_region = "ams"

[build]

[processes]
app = ""
proxy = "proxy"

[mounts]
source = "data"
destination = "/data"
processes = ["app"]
